### ISSUE TITLE
[FE] add progress bar on files upload

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/bucketeer#117]
lets add some progress, after each fulfilled backend request, so lets say we have 100 photos and we upload 10 per request so I would add 10 steps on the bar

**Comment by DeutscherDude** [comment]
[Screencast from 2024-10-18 19-45-18.webm](https://github.com/user-attachments/assets/6cf3bb0d-b824-4e57-885b-09dec1d94bb5)
Thought its nice so added the hover effect :)

**Comment by DeutscherDude** [comment]
https://github.com/cieslarmichal/bucketeer/pull/126

**Comment by cieslarmichal** [comment]
done
