### ISSUE TITLE
[FE] after successfull upload, upload window should be closed

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/bucketeer#120]
After uploading files it should close that window automatically.
![image](https://github.com/user-attachments/assets/8113f121-8b95-4090-a3a5-7672cc31450a)

**Comment by DeutscherDude** [comment]
[Uploading Screencast from 2024-10-18 18-11-55.webm…]()

It seems to, unless that's now what you meant? @cieslarmichal

**Comment by cieslarmichal** [comment]
done
