### ISSUE TITLE
[FE] Video preview & video player

### ISSUE THREAD

**Issue by DeutscherDude** [cieslarmichal/bucketeer#28]

**Comment by DeutscherDude** [comment]
@cieslarmichal 
Video player added.
Video preview for now is just the single frame of the video. This seems to be the default behaviour of the `video` tag ^^.

**Comment by DeutscherDude** [comment]
[Screencast from 2024-08-25 17-55-16.webm](https://github.com/user-attachments/assets/fae7ad8e-fd51-41c9-858b-b3f3a647dfee)

After a bit of testing, I figured out the preview with multiple videos playing :). The trick is to tell the browser explicitly, that the video is to be muted. If it is not specified, the browser will not play the videos.

**Comment by cieslarmichal** [comment]
works as expected
