### ISSUE TITLE
[FE] add uploading files

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/bucketeer#67]

**Comment by DeutscherDude** [comment]
@cieslarmichal - initial version has been prepared.
I am wondering on introducing a bar to simulate progress (yes, simulate for big files & simultaneously catch up once the transfer is confirmed) and a cancellation on exit from the modal (with confirmation required).
Let me know your thoughts :).

**Comment by cieslarmichal** [comment]
I will ley you know once I will test it

**Comment by cieslarmichal** [comment]
works as expected
