### ISSUE TITLE
[BE] test for heavy download

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/bucketeer#68]

**Comment by cieslarmichal** [comment]
blocked by https://github.com/cieslarmichal/bucketeer/issues/67 @DeutscherDude

**Comment by DeutscherDude** [comment]
@cieslarmichal - feel free to test. Maximum file size is controllable via VITE_MAX_FILE_SIZE env variable.

**Comment by cieslarmichal** [comment]
done
