### ISSUE TITLE
[FE] no info about backend error when sending file

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/bucketeer#92]
![image](https://github.com/user-attachments/assets/cd228454-51ba-440a-a95d-13c657df1409)

**Comment by cieslarmichal** [comment]
backend returns 500 and it shows nothing in FE

**Comment by DeutscherDude** [comment]
Added error handling to this modal.

On any error containing `context.reason`:
![image](https://github.com/user-attachments/assets/8ddb421d-2f91-4fa2-a7a2-fb14b56aa71a)

On unexpected error:
![image](https://github.com/user-attachments/assets/54aaaa57-6c9d-4355-bfb9-f9f5c926397d)

**Comment by DeutscherDude** [comment]
@cieslarmichal - merged in https://github.com/cieslarmichal/bucketeer/pull/96
